title: Hei Yang(blog)
SEOTitle:编程爱好者
header-imge:
email:woshiyt1003@gmail.com
descript: "一个挣扎的小白"
keyword: "c++,h5,js,小白慢慢爬"
url: "https://slienceb.github.io"
sidebar: true 
sidebar-about-description: "昨天做梦变成一个牛皮的程序猿！！！！"
sidebar-avatar:
theme: 
